### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Developer-N** [persian-calendar/persian-calendar#1106]
https://github.com/persian-calendar/persian-calendar/blob/06f7258273a4e9313a903da41f39544195656066/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/ui/common/DayPickerView.kt#LL62C10-L62C10

با عرض سلام و خسته نباشید، اگه در قسمت تبدیل تاریخ، میلادی رو انتخاب کنی و ماه رو عوض کنی برنامه کرش میکنه، اینم متن ارور 

Process: com.byagowi.persiancalendar.minApi21.debug, PID: 5271
**java.lang.ArrayIndexOutOfBoundsException: length=30; index=30**
at android.widget.NumberPicker.ensureCachedScrollSelectorValue(NumberPicker.java:2010)
at android.widget.NumberPicker.initializeSelectorWheelIndices(NumberPicker.java:1822)
at android.widget.NumberPicker.setMaxValue(NumberPicker.java:1520)
**at com.byagowi.persiancalendar.ui.common.DayPickerView.reinitializeDayPicker(DayPickerView.kt:62)
at com.byagowi.persiancalendar.ui.common.DayPickerView.binding$lambda$8$lambda$7(DayPickerView.kt:94)**
at com.byagowi.persiancalendar.ui.common.DayPickerView.$r8$lambda$Yu5cyCJoWMKN6Hev6_rQrysjVxk(Unknown Source:0)
at com.byagowi.persiancalendar.ui.common.DayPickerView$$ExternalSyntheticLambda0.onValueChange(Unknown Source:4)
.......

**Comment by ebraminio** [comment]
انتشار جدید تا رفع مشکل متوقف شد و مشکل را برطرف کردم، فوق‌العاده بود، یادم هست قبلاً هم در چنین موقعیتی گزارش باگ داشتید که فوق‌العاده بوده که ممنونم 😊
