### ISSUE TITLE
خطای NullPointerException روی سیستم‌عامل اندروید اتوماتیو

### ISSUE THREAD

**Issue by AlirezaGhadimi** [persian-calendar/persian-calendar#984]
سلام
هنگام اجرا روی اندروید اتوماتیو، با خطای زیر مواجه شدم. لطفا راهنمایی بفرمایید.

`
2022-10-08 10:42:18.960 8019-8019/com.byagowi.persiancalendar.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.byagowi.persiancalendar.debug, PID: 8019
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.byagowi.persiancalendar.debug/com.byagowi.persiancalendar.ui.MainActivity}: java.lang.NullPointerException:  must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException:  must not be null
        at com.byagowi.persiancalendar.utils.UpdateUtilsKt.update(UpdateUtils.kt:171)
        at com.byagowi.persiancalendar.ui.MainActivity.onCreate(MainActivity.kt:121)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
`

**Comment by ebraminio** [comment]
سلام چگونه می‌توانم روی اندروید اتوماتیو پروژه را اجرا کنم که مشکل را ببینم؟ ممنون :)

**Comment by AlirezaGhadimi** [comment]
برای این کار میتونین از امولاتور polestar  استفاده کنید. برای سطح ای.پی.آی ۲۸ و ۲۹ موجود هست.

برای ایجاد یک دستگاه مقلد، در وهله‌ی اول نیاز به ایجاد یک ایمیج سیستمی وجود دارد. یکی از پرکاربردترین ایمیج‌های سیستمی،  ایمیج سیستمی پولستر است که توسط شرکت خودروسازی پولستر ارایه شده است. گام‌های زیر بایستی برای ایجاد این ایمیج سیستمی طی شوند:
الف- در اندروید استودیو، از منوی Tools، گزینه مدیر SDK انتخاب شود.
ب- زبانه SDK Update Sites انتخاب گردد.
پ- جهت اضافه کردن یک سایت آپدیت جدید، دکمه Add انتخاب شود و مقادیر زیر را به عنوان نام و آدرس اضافه کنید.
Name: Polestar 2 System Image
URL: https://developer.polestar.com/sdk/polestar2-sys-img.xml
ت- با تایید و بستن پنجره مدیر SDK، دانلود ایمیج سیستمی گفته‌شده در بالا آغاز می‌گردد.

در ادامه نیاز است تا یک ابزار مجازی اندروید ایجاد شود:

الف- در اندروید استودیو، از منوی ابزارها، گزینه «مدیر ابزار» انتخاب شود و یک ابزار مجازی جدید ایجاد شود.
ب- دکمه «وارد کردن پروفایل سخت‌افزاری» انتخاب شود و مسیر SDK مشخص گردد. این مسیر در داخل زیردایرکتوری system-images وجود دارد و شامل نام Polestar 2 است. در این دایرکتوری، بایستی فایل devices.xml یافت، و وارد گردد.
*مسیر کامل برای دسترسی به فایل:
‍‍‍‍‍~/Android/Sdk/system-images/android-28
پ- پروفایل ایمپورت شده در بخش مربوط به تبلت ظاهر می‌شود. برای ادامه فرآیند بایستی انتخاب شود و دکمه‌ی «بعدی» انتخاب شود.
ت- اکنون روی زبانه x86 images کلیک شود. ایمیج Polestar 2 بایستی در این بخش قابل انتخاب باشد. با انتخاب آن، فرآیند ایجاد ابزار مجازی اندروید برای سیستم‌عامل اندروید اتوماتیو پایان می‌پذیرد.

**Comment by ebraminio** [comment]
توضیحاتتان عالی بود، تا به حال چنین چیزی ندیده بودم، پس از آن چه کار باید کرد، آیا تغییری هم در کد برای اجرا نیاز است؟ ممنونم

**Comment by AlirezaGhadimi** [comment]
خواهش میکنم. 
نه نیازی به تغییری در کد نیست. من در اندروید استودیو اجرایش کردم. نسخه 
android-studio-2021.2.1

**Comment by AlirezaGhadimi** [comment]
سلام، 
آپدیتی  روی این موضوع ندارین؟

**Comment by ebraminio** [comment]
نه، در این ماشین به دلیلی نمی‌تونم اون ایمیج‌هارو نصب کنم

**Comment by AlirezaGhadimi** [comment]
احتمالا مشکل از عدم دسترسی باشه که میتونید از سرویس شکن استفاده کنید  و dns رو ست کنید به موارد زیر:
178.22.122.100
185.51.200.2
‍`
https://shecan.ir/
`
